version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.16.1
    ports:
      - "9901:9901"
      - "9902:9902"
      - "9903:9903"
    volumes:
      - ./envoy.local.yaml:/etc/envoy/envoy.yaml
