apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          # grpc_health_probe won't work with ALTS enabled
          # readinessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50052"]
          # livenessProbe:
          #   exec:
          #     command: ["/bin/grpc_health_probe", "-addr=:50052"]
          image: soeirosantos/alts-payment:v20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - name: grpc
              containerPort: 50052
              protocol: TCP
          env:
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "99"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: fatal
---
# payment.checkout.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
    - port: 50052
      protocol: TCP
      targetPort: 50052
  selector:
    app: payment
