apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-cfg
data:
  envoy.yaml: |-
    admin:
      access_log_path: "/tmp/admin_access.log"
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
    static_resources:
      listeners:
        - address:
            socket_address: { address: 0.0.0.0, port_value: 9902 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: egress_http
                    codec_type: auto
                    route_config:
                      name: payment_service_route
                      virtual_hosts:
                        - name: payment-service
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/pb.PaymentService/Charge"
                              route: { cluster: payment }
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config: {}
        - address:
            socket_address: { address: 0.0.0.0, port_value: 9903 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: egress_http
                    codec_type: auto
                    route_config:
                      name: shipping_service_route
                      virtual_hosts:
                        - name: shipping-service
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/pb.ShippingService/ShipOrder"
                              route: { cluster: shipping }
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config: {}
      clusters:
      - name: payment
        type: STRICT_DNS
        connect_timeout: 0.25s
        dns_refresh_rate: 1s
        http2_protocol_options: {}
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: payment
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: payment.checkout.svc.cluster.local
                    port_value: 50052
        transport_socket:
          name: envoy.transport_sockets.alts
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.alts.v3.Alts
            handshaker_service: "169.254.169.254:8080"
            # the peer sercice accounts is optional if deploying to the same cluster and using the node's SA
            #peer_service_accounts:
            #  - "xxxxxxxxxxxxx-compute@developer.gserviceaccount.com"
      - name: shipping
        type: STRICT_DNS
        connect_timeout: 0.25s
        dns_refresh_rate: 1s
        http2_protocol_options: {}
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: shipping
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: shipping.checkout.svc.cluster.local
                    port_value: 50053

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      volumes:
        - name: envoy-cfg
          configMap:
            name: envoy-cfg
      containers:
        - name: checkout
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50054"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50054"]
          image: soeirosantos/alts-checkout:v21
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - name: grpc
              containerPort: 50054
              protocol: TCP
          env:
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "99"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: fatal
            # - name: PAYMENT_SVC_ADDR
            #   value: payment.checkout.svc.cluster.local:50052
            # - name: SHIPPING_SVC_ADDR
            #   value: shipping.checkout.svc.cluster.local:50053
        - name: envoy
          image: envoyproxy/envoy-alpine:v1.16.1
          volumeMounts:
            - mountPath: /etc/envoy
              readOnly: true
              name: envoy-cfg
          resources:
            requests:
              cpu: 25m
              memory: 75Mi
            limits:
              cpu: 50m
              memory: 150Mi
---
# checkout.checkout.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  ports:
    - port: 50054
      protocol: TCP
      targetPort: 50054
  selector:
    app: checkout
